### ISSUE TITLE
"Lint this view" does not do anything

### ISSUE THREAD

**Issue by hamzamerzic** [SublimeLinter/SublimeLinter-cpplint#11]
Hello. I am using Sublime Text 3 and I have tried setting up cpplint and cppcheck with no success. I followed the instructions per the ReadMe file. I first installed cpplint using pip, then install SublimeLinter plugin and then SublimeLinter-cpplint, both through Package Control. My user settings file looks like this:

```
{
    "user": {
        "debug": false,
        "delay": 0.25,
        "error_color": "D02000",
        "gutter_theme": "Packages/SublimeLinter/gutter-themes/Circle/Circle.gutter-theme",
        "gutter_theme_excludes": [],
        "lint_mode": "background",
        "linters": {
            "cpplint": {
                "@disable": false,
                "args": [],
                "excludes": [],
                "filter": "",
                "linelength": ""
            }
        },
        "mark_style": "outline",
        "no_column_highlights_line": false,
        "passive_warnings": false,
        "paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "python_paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "rc_search_limit": 3,
        "shell_timeout": 10,
        "show_errors_on_save": false,
        "show_marks_in_minimap": true,
        "syntax_map": {
            "html (django)": "html",
            "html (rails)": "html",
            "html 5": "html",
            "javascript (babel)": "javascript",
            "magicpython": "python",
            "php": "html",
            "python django": "python",
            "pythonimproved": "python"
        },
        "warning_color": "DDB700",
        "wrap_find": true
    }
}
```
When I do Lint this view absolutely nothing happens. In the debug mode nothing is printed out in the console and I do not get any windows saying the number of errors. The same thing happens with cppcheck (I also installed it from Package Control the same way). What could be the cause for this?

**Comment by NotSqrt** [comment]
Can you check in debug mode if there's something printed about disabled plugins because they could not find cppcheck or cpplint ?

If that's the case, it's probably a PATH issue.

Refer to http://www.sublimelinter.com/en/latest/troubleshooting.html if you haven't already seen it.

**Comment by hamzamerzic** [comment]
Here is the complete log. After everything loaded I called the "Lint this view option", but nothing changed.

> startup, version: 3103 linux x64 channel: stable
> executable: /opt/sublime_text/sublime_text
> working dir: /
> packages path: /home/hamza/.config/sublime-text-3/Packages
> state path: /home/hamza/.config/sublime-text-3/Local
> zip path: /opt/sublime_text/Packages
> zip path: /home/hamza/.config/sublime-text-3/Installed Packages
> ignored_packages: ["C++", "Vintage"]
> pre session restore time: 0.153016
> loading dictionary Packages/Language - English/en_US.dic
> startup time: 0.34457
> first paint time: 0.36328
> reloading plugin Default.block
> reloading plugin Default.comment
> reloading plugin Default.convert_syntax
> reloading plugin Default.copy_path
> reloading plugin Default.delete_word
> reloading plugin Default.detect_indentation
> reloading plugin Default.duplicate_line
> reloading plugin Default.echo
> reloading plugin Default.exec
> reloading plugin Default.fold
> reloading plugin Default.font
> reloading plugin Default.goto_line
> reloading plugin Default.history_list
> reloading plugin Default.indentation
> reloading plugin Default.kill_ring
> reloading plugin Default.mark
> reloading plugin Default.new_templates
> reloading plugin Default.open_context_url
> reloading plugin Default.open_file_settings
> reloading plugin Default.open_in_browser
> reloading plugin Default.pane
> reloading plugin Default.paragraph
> reloading plugin Default.paste_from_history
> reloading plugin Default.profile
> reloading plugin Default.profile_syntax_definition
> reloading plugin Default.quick_panel
> reloading plugin Default.run_syntax_tests
> reloading plugin Default.save_on_focus_lost
> reloading plugin Default.scroll
> reloading plugin Default.set_unsaved_view_name
> reloading plugin Default.side_bar
> reloading plugin Default.sort
> reloading plugin Default.swap_line
> reloading plugin Default.switch_file
> reloading plugin Default.symbol
> reloading plugin Default.transform
> reloading plugin Default.transpose
> reloading plugin Default.trim_trailing_white_space
> reloading plugin CSS.css_completions
> reloading plugin Diff.diff
> reloading plugin HTML.encode_html_entities
> reloading plugin HTML.html_completions
> reloading plugin Python.syntax_test_python
> reloading plugin 0_package_control_loader.00-package_control
> reloading plugin 0_package_control_loader.01-ssl-linux
> Package Control: Linux SSL: successfully loaded _ssl module for libssl.so.1.0.0
> reloading plugin 0_package_control_loader.02-bz2
> reloading plugin 0_package_control_loader.50-backrefs
> reloading plugin BracketHighlighter.bh_core
> reloading plugin BracketHighlighter.bh_logging
> reloading plugin BracketHighlighter.bh_plugin
> reloading plugin BracketHighlighter.bh_regions
> reloading plugin BracketHighlighter.bh_remove
> reloading plugin BracketHighlighter.bh_rules
> reloading plugin BracketHighlighter.bh_search
> reloading plugin BracketHighlighter.bh_swapping
> reloading plugin BracketHighlighter.bh_wrapping
> reloading plugin Package Control.1_reloader
> reloading plugin Package Control.2_bootstrap
> reloading plugin Package Control.Package Control
> reloading plugin SideBarEnhancements.SideBar
> reloading plugin SideBarEnhancements.SideBarAPI
> reloading plugin SideBarEnhancements.SideBarDefaultDisable
> reloading plugin SublimeLinter-cpplint.linter
> SublimeLinter: cpplint linter loaded 
> reloading plugin SublimeSwitchFileDeluxe.switch_file_deluxe
> reloading plugin Anaconda.anaconda
> reloading plugin Anaconda.version
> reloading plugin Cheat Sheets.cheat-sheets
> reloading plugin SublimeLinter.commands
> reloading plugin SublimeLinter.sublimelinter
> plugins loaded
> SublimeLinter: debug mode: on 
> SublimeLinter: temp directory: /tmp/SublimeLinter3-hamza 
> Package Control: Skipping automatic upgrade, last run at 2016-04-14 12:23:23, next run at 2016-04-14 13:23:23 or after
>

**Comment by NotSqrt** [comment]
OK, looks good.

Nothing happens when saving the file ?

What is the extension of your file ? What is the syntax detected by SublimeText (bottom right of the window) ?

**Comment by hamzamerzic** [comment]
Nothing happens. The extensions I tried are .cc and .cpp. I tried the example for cppcheck with the test.cpp file, but nothing happened. The syntax detects C++11 as I have a "C++11" plugin.

**Comment by NotSqrt** [comment]
That's probably the issue.
The linter will only run on files with ``syntax = 'c++'``.

In "syntax_map", add ``"C++11": "c++"``, and you should be good.

If that works, I will add this in the code.

**Comment by hamzamerzic** [comment]
Ok, when I changed to "C++" it did work, but adding it in the syntax_map did not :/

**Comment by NotSqrt** [comment]
Have you tried in lower case : ``"c++11": "c++"`` ?
It seems to work for me !

**Comment by hamzamerzic** [comment]
It works with lower case. Thank you!
