### ISSUE TITLE
realtime linting

### ISSUE THREAD

**Issue by junliu111** [SublimeLinter/SublimeLinter-cpplint#16]
SublimeLinter-cpplint only works when the file is saved. Is there a way to make it work while typing? thanks.

**Comment by kaste** [comment]
`cpplint` does not support linting via stdin, it only lints files on disk. 🤷‍♀ 

Feel free to reopen if you know a workaround.

**Comment by junliu111** [comment]
@kaste Is there anyone that can lint files while typing? thanks.

**Comment by kaste** [comment]
gcc and clang
