### ISSUE TITLE
'array' file not found

### ISSUE THREAD

**Issue by juanfal** [SublimeLinter/SublimeLinter-cpplint#4]
I've been using (and enjoying it!!) SublimeLinter-cpplint for long.  Now I am reckoning the idea of using #include <array> from the tr1 STL, as part of the material for our subject.  It seems everything compiles correctly but, the linter is all the time saying to me that for the included file

    'array' file not found

although the rest of the file is clean and without any warnings and compiles and executes perfectly well:

![captura de pantalla 2015-02-23 a las 11 04 35](https://cloud.githubusercontent.com/assets/895596/6325841/d107e39c-bb4b-11e4-94de-a3ca699e2863.png)

**Comment by juanfal** [comment]
I've forgotten the configuration file:

![captura de pantalla 2015-02-23 a las 11 06 37](https://cloud.githubusercontent.com/assets/895596/6325871/1c6ddfbc-bb4c-11e4-8e9f-8cbf6b74fe44.png)

**Comment by NotSqrt** [comment]
Try calling cpplint yourself on your file.
If you see this error, then there's nothing I can do about it, cpplint do indeed trigger this warning, the problem is in cpplint, not SublimeLinter-cpplint.
If you don't see the error, then it's probably a problem in how I call cpplint.
