### ISSUE TITLE
do not use .cpp as tempfile_suffix

### ISSUE THREAD

**Issue by thiagolacerda** [SublimeLinter/SublimeLinter-cpplint#5]
cpplint behaviors differently, depending on the filename extension. For .h files it has a set of checks which is different from those in .cpp files.
Using .cpp as tempfile_suffix will mess this when scanning for a .h file.
You can easily reproduce the behavior by calling cpplint in a header in command line and  then calling the lint for the same file in sublime.
I think that changing tempfile_suffix to '-' instead of '.cpp' might fix the issue

**Comment by rchl** [comment]
See #1 also which suggests more generic solution to the problem.

**Comment by NotSqrt** [comment]
Done !
