### ISSUE TITLE
cpplint cannot find standard c library

### ISSUE THREAD

**Issue by jiangyuanhk** [SublimeLinter/SublimeLinter-cpplint#6]
Hey, I am actually not sure if I should post the issue here. 
I've downloaded and installed cpplint in /usr/local/bin/cpplint
and also put the path "/usr/lib/libc.dylib" in the user-setting file of sublimeLinter (I am using 10.10 Yosemite in MaxOS and treating it as the path to the standard c library on Mac)

I also changed the recursive finding index to be large enough to cover all the files in my project root directory. 

But the linter cannot still find the Std Library, and gives an error on the first line of my project when I try to include <stdio.h>.
Also, it's worth noted that above error is the only highlighted error throughout of my c file. I intentionally typed something wrong in the following lines but the linter does not report errors.

**Comment by NotSqrt** [comment]
Can you switch SublimeLinter to debug mode, look at the command called by the linter, and try it yourself in a shell ?

This is probably an issue with cpplint itself, and I won't be able to help you with this ..
